// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbnUXD-YIpaompI5lP3V1_0RI8AneaySU',
    appId: '1:340514439542:web:8a8c81d577a5cbec897a57',
    messagingSenderId: '340514439542',
    projectId: 'swayam-9b4c4',
    authDomain: 'swayam-9b4c4.firebaseapp.com',
    storageBucket: 'swayam-9b4c4.appspot.com',
    measurementId: 'G-DME35BZN3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS-Zp6eAS83shziDF39oKAEEyk3C0QjMw',
    appId: '1:340514439542:android:ea69989e07e56af1897a57',
    messagingSenderId: '340514439542',
    projectId: 'swayam-9b4c4',
    storageBucket: 'swayam-9b4c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWcrWoPlC9fVfKd1sPqUy7hTIRnl84KSw',
    appId: '1:340514439542:ios:d0d953f2bfc38d83897a57',
    messagingSenderId: '340514439542',
    projectId: 'swayam-9b4c4',
    storageBucket: 'swayam-9b4c4.appspot.com',
    iosBundleId: 'com.example.swayam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWcrWoPlC9fVfKd1sPqUy7hTIRnl84KSw',
    appId: '1:340514439542:ios:d0d953f2bfc38d83897a57',
    messagingSenderId: '340514439542',
    projectId: 'swayam-9b4c4',
    storageBucket: 'swayam-9b4c4.appspot.com',
    iosBundleId: 'com.example.swayam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbnUXD-YIpaompI5lP3V1_0RI8AneaySU',
    appId: '1:340514439542:web:29799d15d0ea1f59897a57',
    messagingSenderId: '340514439542',
    projectId: 'swayam-9b4c4',
    authDomain: 'swayam-9b4c4.firebaseapp.com',
    storageBucket: 'swayam-9b4c4.appspot.com',
    measurementId: 'G-HK85XRTL0C',
  );
}
